# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a463243ce1f1d9946b887e8bf2c2b22270caf807e3e896ae0023221e7273a952201bdfad91da4693ad06016f28c660841c662b9e32ac28f31848748b8ba293f

test:
  secret_key_base: 78fb8afa4f463286d5e4f639e967ded2e26f77c4ebab07d90b1893706b3df7f9e2f1abf6264db0792158e80f927da1a79accc35119ec35decf0b99db3f81a699

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
